In [1]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)

arr2 = np.arange(0, 21)
print(arr2)

arr3 = np.linspace(1, 5, 10)
print(arr3)


[10 20 30 40 50]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [3]:
zeros_arr = np.zeros((3, 3))
print(zeros_arr)

ones_arr = np.ones((2, 4))
print(ones_arr)

empty_arr = np.empty((2, 2))
print(empty_arr)

identity_arr = np.identity(3)
print(identity_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1.22437461e-307 9.12583812e-308]
 [1.02950923e-295             nan]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

arr2_new = np.arange(0, 20)
reshaped_arr = arr2_new.reshape(4, 5)
print(reshaped_arr)

(5,)
(21,)
(10,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [4]:
import numpy as np
conditions = [
    arr1 < 10,
    (arr1 >= 10) & (arr1 <= 30),
    arr1 > 30
]
choices = ["Low", "Medium", "High"]
classified = np.select(conditions, choices, default="Unknown")

print("Classified values for arr1:")
print(classified)

Classified values for arr1:
['Medium' 'Medium' 'Medium' 'High' 'High']
